allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@aws-cdk/cloud-assembly-schema@53.25.0'
  - aws-cdk-lib@2.256.0
  - aws-cdk@2.1123.0
  - ts-jest@29.4.10
  - js-yaml@4.1.2
overrides:
  js-yaml@<=4.1.1: ^4.1.2
