allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@aws-cdk/cloud-assembly-schema@53.25.0'
  - aws-cdk-lib@2.256.0
  - aws-cdk@2.1123.0
  - ts-jest@29.4.10
  - js-yaml@4.1.2
  - brace-expansion@1.1.16 || 1.1.17 || 1.1.18
  - '@orcabus/platform-cdk-constructs@1.9.3'
overrides:
  browserslist@<=4.28.6: ^4.28.7
